# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
orbs:
  # Use the official Heroku orb to deploy your app to Heroku.
  # See: https://circleci.com/developer/orbs/orb/heroku/heroku
  heroku: circleci/heroku@2.0.0

jobs:
  # Define a job to run your RSpec tests.
  rspec:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3
      - run:
          name: Run RSpec tests
          command: rspec
    # Only run this job when code is pushed to the main branch.
    # You can modify this to suit your needs.
    

  # Define a job to deploy your app to Heroku.
  deploy:
    # Use the Heroku orb to deploy your app to Heroku.
    # You'll need to configure the HEROKU_API_KEY environment variable in your CircleCI project settings.
    # See: https://devcenter.heroku.com/articles/platform-api-quickstart
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy:
          app-name: events-attendees
    # Only run this job when code is pushed to the master branch and the RSpec tests pass.
    # You can modify this to suit your needs.
    # requires:
    #   - rspec
    

workflows:
  version: 2
  # Define a workflow that runs the RSpec tests and then deploys the app to Heroku.
  test-and-deploy:
    jobs:
      - rspec
      - deploy:
          requires:
            - rspec