development:
  adapter: postgresql
  database: EventsAttendees
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: EventsAttendees
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: EventsAttendees
  pool: 5
  timeout: 5000
  host: localhost